### ISSUE TITLE
我照着你的步骤写,还是只能运行node端的代码,react部分依然没运行

### ISSUE THREAD

**Issue by acs121** [boychina/yarn-react-express#1]
```
acs@acs-X550JX:~/桌面/creat-msgboard/test-app$ yarn start
yarn start v1.0.1
$ concurrently "yarn react-start" "cd server && yarn start"
[0] module.js:487
[0]     throw err;
[0]     ^
[0]
[0] Error: Cannot find module '/home/acs/桌面/creat-msgboard/test-app/scripts/start.js'
[0]     at Function.Module._resolveFilename (module.js:485:15)
[0]     at Function.Module._load (module.js:437:25)
[0]     at Function.Module.runMain (module.js:605:10)
[0]     at startup (bootstrap_node.js:158:16)
[0]     at bootstrap_node.js:575:3
error Command failed with exit code 1.
[0] yarn react-start exited with code 1
[1] [nodemon] 1.12.0
[1] [nodemon] to restart at any time, enter `rs`
[1] [nodemon] watching: *.*
[1] [nodemon] starting `node ./bin/www```
```
就是我的node scripts/start.js找不到文件

**Comment by boychina** [comment]
你好，你可能应该需要执行一下`npm run eject`

**Comment by Jeral-Xue** [comment]
遇到同样问题，执行npm run eject不行
